# Build stage
FROM golang:1.25-bookworm AS builder

# Install build dependencies
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN go install github.com/magefile/mage@v1.15.0

WORKDIR /build

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o meshtastic-mqtt-relay ./cmd/meshtastic-mqtt-relay
RUN CGO_ENABLED=0 mage build:release

# Runtime stage
FROM debian:bookworm-slim
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN apt-get update && apt-get install -y ca-certificates curl tini && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy binary from builder
COPY --from=builder /build/artifacts/build/release/${TARGETPLATFORM}/meshtastic-mqtt-relay .
COPY docker/entrypoint.sh .

ENV HEALTHCHECK_PORT=8099
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl", "--fail", "http://localhost:${HEALTHCHECK_PORT}/" ]
# # Run as non-root user
# RUN adduser -D -u 1000 appuser
# USER appuser

# Expose any necessary ports (none required for MQTT client)

ENTRYPOINT ["/app/entrypoint.sh"]
